### ISSUE TITLE
Simulator doesn't work 

### ISSUE THREAD

**Issue by YousefSaber** [jurem/SicTools#8]
Ubuntu 19.10 
```
(base) joseph@joseph-X541UJ:~/Documents/SIC - Code$ java -jar sictools.jar 
Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2032)
        at javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1158)
        at javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:431)
        at javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:148)
        at javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1577)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:579)
        at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1349)
        at javax.swing.UIManager.initialize(UIManager.java:1459)
        at javax.swing.UIManager.maybeInitialize(UIManager.java:1426)
        at javax.swing.UIManager.getUI(UIManager.java:1006)
        at javax.swing.JPanel.updateUI(JPanel.java:126)
        at javax.swing.JPanel.<init>(JPanel.java:86)
        at javax.swing.JPanel.<init>(JPanel.java:109)
        at javax.swing.JPanel.<init>(JPanel.java:117)
        at sic.sim.views.CPUView.$$$setupUI$$$(CPUView.java:183)
        at sic.sim.views.CPUView.<init>(CPUView.java:172)
        at sic.sim.MainView.<init>(MainView.java:60)
        at sic.Sim.main(Sim.java:54)
(base) joseph@joseph-X541UJ:~/Documents/SIC - Code$ java -version
openjdk version "1.8.0_232-ea"
OpenJDK Runtime Environment (build 1.8.0_232-ea-8u232-b09-0ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

**Comment by jakoberzar** [comment]
Hello @YousefSaber,
after a quick search online, it may be connected to the jdk package on your system.

Have you tried the fixes mentioned in [this discussion on GitHub](https://github.com/Microsoft/vscode-arduino/issues/644) or [this Ask Ubuntu thread](https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror)?

Hope this helps.

**Comment by YousefSaber** [comment]
> Hello @YousefSaber,
> after a quick search online, it may be connected to the jdk package on your system.
> 
> Have you tried the fixes mentioned in [this discussion on GitHub](https://github.com/Microsoft/vscode-arduino/issues/644) or [this Ask Ubuntu thread](https://askubuntu.com/questions/695560/assistive-technology-not-found-awterror)?
> 
> Hope this helps.

@YousefSaber 
it worked thanks a lot I'm sorry I didn't google this issue in the first time 

![image](https://user-images.githubusercontent.com/33742499/68316484-391bcc80-00c2-11ea-8829-7662afd1d339.png)
